CODE_SUCCESSFUL_AUTHENTICATION = 200
CODE_INCORRECT_CREDENTIALS = 501
CODE_MESSAGE_CORRUPTED = 502
CODE_SIGN_UP_ERROR = 503
CODE_INTERNAL_SERVER_ERROR = 500
CODE_EXITING_AUTHORIZED = 201
CODE_INVALID_FORMAT = 504

STATUS_SUCCESSFUL_AUTHENTICATION = 'Successful authentication'
STATUS_INCORRECT_CREDENTIALS = 'Incorrect credentials'
STATUS_MESSAGE_CORRUPTED = 'Message corrupted'
STATUS_SIGN_UP_ERROR = 'Sign up error'
STATUS_INTERNAL_SERVER_ERROR = 'Internal Server Error'
STATUS_EXITING_AUTHORIZED = 'Exiting authorized'
STATUS_INVALID_FORMAT = 'Invalid format'
